name: Build client

on:
  push:
    branches: dev
  pull_request:
    branches: dev

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache build client
        uses: actions/cache@v3
        with:
          path: ./client/build
          key: ${{ runner.os }}-client-${{ hashFiles('**/client/CMakeLists.txt') }}
          restore-keys: ${{ runner.os }}-client-

      - name: Build client
        run: ./build.sh client

      - name: Check binaries
        run: |
          if [ ! -f ./rtype_client ]; then
            echo "::error file=./rtype_client::client binary does not exist"
            exit 1
          else
            echo "::notice::All binaries OK"
          fi

  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache build client
        uses: actions/cache@v3
        with:
          path: ./client/build
          key: ${{ runner.os }}-client-${{ hashFiles('**/client/CMakeLists.txt') }}
          restore-keys: ${{ runner.os }}-client-

      - name: Build client
        run: ./build.ps1 client

      - name: Check binaries
        run: |
          if (-Not (Test-Path "./rtype_client.exe")) {
            Write-Host "Client binary does not exist"
            exit 1
          } else {
            Write-Host "All binaries OK"
          }